# Generated by Django 4.2.29 on 2026-04-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attack_defense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnbox_name', models.CharField(help_text='e.g. Team A VulnBox', max_length=100)),
                ('vulnbox_ip', models.GenericIPAddressField()),
                ('web_port', models.IntegerField(default=80)),
                ('ssh_port', models.IntegerField(default=22)),
                ('target_team', models.ForeignKey(blank=True, help_text='The team this team is assigned to attack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by', to='accounts.team')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_assignment', to='accounts.team')),
            ],
        ),
    ]
