# Generated by Django 4.2.29 on 2026-04-24 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_defense', '0002_arenaassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenaassignment',
            name='ad_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arenaassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 24, 23, 47, 26, 738806, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arenaassignment',
            name='flag',
            field=models.CharField(default='ihack{default}', max_length=255),
        ),
    ]
