# Generated by Django 4.2.29 on 2026-06-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_defense', '0004_uptimelog_alter_arenaassignment_flag_adsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsession',
            name='defense_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsession',
            name='is_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adsession',
            name='last_submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnboxstatus',
            name='last_flag_rotation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnboxstatus',
            name='uptime_ticks',
            field=models.IntegerField(default=0),
        ),
    ]
