# Generated by Django 4.2.29 on 2026-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_defense', '0005_adsession_defense_points_adsession_is_captured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
